# Advanced NumPy Concepts

**np.arange()**

The np.arange() function in NumPy is used to create sequences of numbers with specified start, stop, and step values. It is similar to Python's range() but offers more flexibility, especially with floating-point numbers.

**Syntax:**

np.arange([start,] stop[, step], dtype=None)

**Parameters**

- start (optional): Starting value of the sequence (inclusive). Default is 0.
- ftop (required): End value of the sequence (exclusive).
- step (optional): Spacing between values (default is 1).
- dtype (optional): Desired data type of the output array (inferred by default).

Examples

## Basic Usage

Generate an array from 0 (default start) to 9 (stop, exclusive):

In [1]:
import numpy as np

import sys

print(sys.executable)

/Volumes/SSD1/AimerzAI/AimerAI-Data-Science/.venv/bin/python3.14


In [2]:
array1 = np.arange(10)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


## Specifying Start and Stop

Create n array from 5 to 14:

In [3]:
array2 = np.arange(5,15)
print(array2)

[ 5  6  7  8  9 10 11 12 13 14]


## Using Step

Generate an array with a step size of 2

In [4]:
array3 = np.arange(2,10,2)
print(array3)

[2 4 6 8]


## Specifying Data Type

Generate an array with a specific data type

In [5]:
array4 = np.arange(1,6,dtype=float)
print(array4)

[1. 2. 3. 4. 5.]


## Combining Arrays

Combining arrays involves merging two or more arrays into one. This can be done along different axes (vertical or horizontal).

### Vertical Stacking (np.vstack):

This method stacks arrays along the vertical axis (row-wise), creating a new array where the original arrays are placed one below the other.

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [7]:
vstacked = np.vstack((a,b))
print("Vertically Stacked Array:\n", vstacked)

Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]]


- np.vstack((a, b)) combines a and b vertically.
- The result is a 2D array where the first row is a and the second row is b.

### Horizontal Stacking (np.hstack)

This method stacks arrays along the horizontal axis (column-wise), creating a new array where the original arrays are placed side-by-side.

In [8]:
hstacked = np.hstack((a,b))
print("Horizontally Stacked Array:\n", hstacked)

Horizontally Stacked Array:
 [1 2 3 4 5 6]


- np.hstack((a, b)) combines a and b horizontally.
- The result is a 1D array where elements of b follow elements of a.

### Column Stacking (np.column_stack)

This method combines 1D arrays into a 2D array by treating each array as a column.

In [9]:
cstacked = np.column_stack((a,b))
print("Column Stacked Array:\n", cstacked)

Column Stacked Array:
 [[1 4]
 [2 5]
 [3 6]]


- np.column _stack((a, b)) treats a and b as columns of a 2D array.
- The result is a 2D array where each element of a is paired with the corresponding element of b.

## Splitting Arrays

### np.split() Splits an array into multiple sub-arrays along a specified axis.

In [10]:
arr = np.arange(1, 13).reshape (3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Split into 3 subarrays along rows

split = np.split(arr, 3)
print("Split into subarrays: \n", split)

Split into subarrays: 
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


## Horizontal Splitting (np.hsplit)

Splits an array along the horizontal axis (columns).

In [12]:
# Horizontal splitting

hsplit = np.hsplit(arr, 2)
print("Horizontally split arrays: \n", hsplit)

Horizontally split arrays: 
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


## Vertical Splitting (np.vsplit)

Splits an array along the vertical axis (rows).

In [13]:
# Vertical splitting

vsplit = np.vsplit(arr, 3)
print("Vertically split arrays: \n", vsplit)

Vertically split arrays: 
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


## Numpy Statistical Functions

NumPy provides a wide range of statistical functions that make it easy to perform descriptive and inferential statistics on large datasets. These functions help in calculating measures of central tendency, dispersion, and other essential statistical values.

In [14]:
data = np.array([3,7,1,5,9])

print(data)

[3 7 1 5 9]


### Min and Max (np.min and fip.max)

These functions return the minimum and maximum values in an array.

In [15]:
min_value = np.min(data)
max_value = np.max (data)
print("Min: ", min_value)
print("Max: ", max_value)

Min:  1
Max:  9


### Mean (np.mean)

The mean (average) is the sum of all elements divided by the number of elements. It gives an idea of the central value in a dataset.

In [16]:
mean_value = np.mean(data)

print("Mean: ", mean_value)

Mean:  5.0


### Median (np.median)

The median is the middle value of a dataset, which separates it into two equal halves. It's less affected by outliers than the mean.

In [17]:
data = np.array([2,4,6,8,100])

median_value = np.median(data)

print("Median: ", median_value)

Median:  6.0


### Standard Deviation (np.std)

Standard deviation measures the spread of data around the mean. A low standard deviation means the data points are close to the mean, while a high value indicates a wider spread.

In [18]:
data = np.array([2,4,6,8,10])

In [19]:
std_dev_value = np.std(data)

print("Standard Deviation Value: ", std_dev_value)

Standard Deviation Value:  2.8284271247461903


### Variance (np.var)

Variance is the square of the standard deviation and measures the dispersion of data points. It's useful in determining how much the data varies.

In [20]:
variance_val = np.var(data)

print("Variance Value: ", variance_val)

Variance Value:  8.0


### Percentile (np.percentile)

Percentiles indicate the relative standing of a value within a dataset. For instance, the 25th percentile is the value below which 25% of the data falls.

In [21]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

In [22]:
percentile_25 = np.percentile(data, 25)
percentile_50 = np.percentile(data, 50)
percentile_75 = np.percentile(data, 75)
percentile_80 = np.percentile(data, 80)
print("25th percentile: ", percentile_25)
print("50th percentile: ", percentile_50)
print("75th percentile: ", percentile_75)
print("80th percentile: ", percentile_80)

25th percentile:  3.25
50th percentile:  5.5
75th percentile:  7.75
80th percentile:  8.2


## Random Number Generation

The NumPy random module is used to generate random numbers in a variety of ways. This can be crucial for simulations, testing models, or creating randomized data for machine learning.

### rand() - Generating Random Numbers Between 0 and 1

The np.random.rand() function generates random numbers from a uniform distribution between 0 and 1.

In [23]:
random_number = np.random.rand()
print("Random Number: ", random_number)

Random Number:  0.864021468577267


### Generate an Array with Random Numbers

In [24]:
random_array = np.random.rand(2,3)
print("Random Array:\n", random_array)

Random Array:
 [[0.23945188 0.11346774 0.25001093]
 [0.79745787 0.21068042 0.39043971]]


- np.random.rand() generates numbers between 0 and 1.
- If you provide dimensions, like (2, 3), it creates a 2x3 array of random numbers.

### randint() - Generating Random Integers

The np.random.randint() function generates random integers. You can specify the range and the size of the output.

- low is the lower bound of the random integers.
- high is the upper bound (exclusive).
- size specifies the shape of the output array.

In [25]:
random_int = np.random.randint(0, 10)
print("Random Integer: ", random_int)

Random Integer:  4


In [26]:
random_int_array = np.random.randint(0,100,(2,3))
print("Random Integer Array:\n", random_int_array)

Random Integer Array:
 [[22 13 40]
 [67 16 73]]


- np.random.randint(0, 10) generates integers between 0 and 10 (exclusive).
- np.random.randint(1, 100, (2, 3)) generates a 2x3 array of integers between 1 and 100.

## Handling Missing Data in NumPy Arrays

Handling missing data is a common task in data processing, as real-world data often contains incomplete or missing values. NumPy, while not specifically designed for handling missing data (as this is more naturally handled in libraries like Pandas), provides several ways to manage missing values using placeholders like NaN (Not a Number) or masked arrays

### Identifying NaN Values :

The np.nan constant is used to denote missing values in arrays, and np.isnan() helps detect these values.

In [27]:
data = np.array([1,2,np.nan,np.nan,4,np.nan,6])

In [28]:
nan_mask = np.isnan(data)
print("NaN Mask:\n", nan_mask)

NaN Mask:
 [False False  True  True False  True False]


- This mask shows True where NaN values are present and False elsewhere.

### Removing Missing Values:

If you want to work with only the non-missing values, you can filter them out.

In [29]:
data_no_nan = data[~np.isnan(data)]
print("Data without NaN:\n", data_no_nan)

Data without NaN:
 [1. 2. 4. 6.]


### Filling Missing Values:

In some cases, it's useful to replace missing values with a specific number, such as the mean or median of the data, or a fixed value like 0.

In [30]:
mean_value = np.nanmean(data)

data_filled = np.where(np.isnan(data), mean_value, data)
print("Data with NaN filled:\n", data_filled)

Data with NaN filled:
 [1.   2.   3.25 3.25 4.   3.25 6.  ]


Here, np.nanmean(data) calculates the mean while ignoring NaN values, and np.where() replaces NaN values with the calculated mean.