In [1]:
import numpy as np

## Vectors and its Operations

In [2]:
vector_a = np.array([3,4])
vector_b = np.array([1,2])

In [3]:
vector_add = vector_a + vector_b
vector_sub = vector_a - vector_b

print("Vector Addition: ", vector_add)
print("Vector Subtraction: ", vector_sub)

Vector Addition:  [4 6]
Vector Subtraction:  [2 2]


In [4]:
dot_product = np.dot(vector_a, vector_b)
print("Dot Product of two vectors: ", dot_product)

Dot Product of two vectors:  11


## Matrix and its Operations

### Matrix Addition and Subtraction

In [6]:
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])

In [7]:
matrix_add = matrix_a + matrix_b
matrix_sub = matrix_a - matrix_b

print("Matrix Addition: \n", matrix_add)
print("Matrix Subtraction: \n", matrix_sub)

Matrix Addition: 
 [[ 6  8]
 [10 12]]
Matrix Subtraction: 
 [[-4 -4]
 [-4 -4]]


### Matrix Multiplication

In [ ]:
matrix_prod = np.matmul(matrix_a, matrix_b)
print("Matrix Multiplication:\n", matrix_prod)
print("Matrix Multiplication using '@' operator:\n", matrix_a @ matrix_b)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Multiplication using '@' operator:
 [[19 22]
 [43 50]]


### Determinant and Inverse of a Matrix

In [10]:
matrix_a = np.array([[1,2],[3,4]])

#### Determinant of a Matrix

- It is a scalar value that can be computed from the elements of a square matrix and encodes certain properties of the matrix.
- The determinant of a matrix provides information about the matrix, such as whether it is invertible (non-singular) or not (singular). If the determinant is zero, the matrix is singular and does not have an inverse. If the determinant is non-zero, the matrix is non-singular and has an inverse.

In [11]:
determinant = np.linalg.det(matrix_a)
print("Determinant of Matrix A: ", determinant)

Determinant of Matrix A:  -2.0000000000000004


#### Matrix Inverse

- The inverse of a matrix A is denoted as A^(-1) and is defined such that A * A^(-1) = I, where I is the identity matrix.

In [12]:
matrix_inv = np.linalg.inv(matrix_a)

print("Inverse of Matrix A:\n", matrix_inv)

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Transpose of a Matrix

- The transpose of a matrix A, denoted as A^T, is obtained by swapping the rows and columns of the matrix. If A is an m x n matrix, then A^T is an n x m matrix. The element at the i-th row and j-th column of A becomes the element at the j-th row and i-th column of A^T.

In [13]:
A = np.array([[1,2,3],[4,5,6]])

In [14]:
A_transpose = A.T
print("Transpose of Matrix A:\n", A_transpose)

Transpose of Matrix A:
 [[1 4]
 [2 5]
 [3 6]]


## Eigenvalues and Eigenvectors

### Eigen Vectors

- Eigenvectors are special vectors that, when we apply a transformation (like rotating, stretching, or shrinking) to them, do not change their direction. They may get longer or shorter, but they still point in the same direction.